version: '3.8'

services:
  minio:
    build:
      context: .
      dockerfile: ./services/minio/Dockerfile
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: MEGASCATTERBOMB
      MINIO_ROOT_PASSWORD: masterbase
    volumes:
      - demo_data:/blobs/

  db:
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    container_name: db
    depends_on:
      - s3
    environment:
      MINIO_HOST: s3
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: MEGASCATTERBOMB
      MINIO_SECRET_KEY: masterbase

      POSTGRES_USER: MEGASCATTERBOMB
      POSTGRES_PASSWORD: masterbase
      POSTGRES_DB: demos
    ports:
      - "8050:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
      args:
        DEVELOPMENT: ${DEVELOPMENT}
    container_name: api
    environment:
      DEVELOPMENT: ${DEVELOPMENT}
      DEBUG_WAIT_FOR_ATTACH: ${DEBUG_WAIT_FOR_ATTACH}
      STEAM_API_KEY: ${STEAM_API_KEY}
      POSTGRES_USER: MEGASCATTERBOMB
      POSTGRES_PASSWORD: masterbase
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MINIO_HOST: localhost
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: MEGASCATTERBOMB
      MINIO_SECRET_KEY: masterbase
    ports:
      - "8000:8000"


networks:
  masterbase_default:
    driver: bridge

volumes:
  demo_data:
  db_data: