version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: db
    environment:
      POSTGRES_USER: MEGASCATTERBOMB
      POSTGRES_PASSWORD: masterbase
      POSTGRES_DB: demos
    networks:
      masterbase-network-dev:
        ipv4_address: 172.20.1.10
    ports:
      - "8050:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        DEVELOPMENT: ${DEVELOPMENT}
    container_name: api
    environment:
      STEAM_API_KEY: ${STEAM_API_KEY}
      POSTGRES_USER: MEGASCATTERBOMB
      POSTGRES_PASSWORD: masterbase
      POSTGRES_HOST: 172.20.1.10
      POSTGRES_PORT: 5432
    networks:
      masterbase-network-dev:
        ipv4_address: 172.20.1.20
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      masterbase-network-dev:
        ipv4_address: 172.20.1.30
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      masterbase-network-dev:
        ipv4_address: 172.20.1.40
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  masterbase-network-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
