version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:16.1-bullseye
    environment:
      POSTGRES_DB: demos
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
        - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
