version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:16.1-bullseye
    environment:
      POSTGRES_DB: demos
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
        - 8001:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: demos
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: pdm run alembic upgrade head && pdm run litestar --app-dir src/api run --host 0.0.0.0
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - api:/data

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/demos?sslmode=disable"
    links:
      - postgres
      - prometheus

volumes:
  postgres:
    driver: local
  api:
    driver: local
