name: Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      python-version: ${{ steps.setup-python.outputs.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install pdm
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdm

      - name: Install dependencies
        run: pdm sync -G:all
