name: Python 3.11 Test

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Python
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pdm
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdm

    - name: Install dependencies
      run: pdm sync -G:all

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      run: pdm run pytest

  lint:
    name: Lint/Mypy
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: ruff
      run: pdm run ruff check masterbase --output-format=github

    - name: mypy
      run: pdm run mypy
