name: Python 3.11 Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test with Python 3.11
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install pdm
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdm

    - name: Install dependencies
      run: pdm sync -G:all

    - name: Run tests
      run: pdm run pytest
