name: Python 3.11 Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test with Python 3.11
    runs-on: ubuntu-latest

    steps:
      - name: Call Setup
        uses: ./.github/workflows/setup.yml@main

      - name: Run tests
        run: pdm run pytest
